// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<Record<string, string>>;

export function ClearTarget():Promise<string>;

export function CoreRunning():Promise<boolean>;

export function CoreStatus():Promise<Record<string, any>>;

export function EnvDetect():Promise<Record<string, any>>;

export function ExportDiagnostics():Promise<string>;

export function LoadConfig():Promise<main.Config>;

export function OpenLogDir():Promise<string>;

export function PickDir(arg1:string):Promise<string>;

export function PollLogs():Promise<Array<string>>;

export function SaveConfig(arg1:main.Config):Promise<string>;

export function StartCore():Promise<string>;

export function StopCore():Promise<string>;

export function TailLog():Promise<Array<string>>;

export function Version():Promise<string>;
