// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Calibrate(arg1, arg2, arg3) {
  return window['go']['main']['App']['Calibrate'](arg1, arg2, arg3);
}

export function CoreRunning() {
  return window['go']['main']['App']['CoreRunning']();
}

export function CoreStatus() {
  return window['go']['main']['App']['CoreStatus']();
}

export function EnvDetect() {
  return window['go']['main']['App']['EnvDetect']();
}

export function ExportDiagnostics() {
  return window['go']['main']['App']['ExportDiagnostics']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenLogDir() {
  return window['go']['main']['App']['OpenLogDir']();
}

export function PickDir(arg1) {
  return window['go']['main']['App']['PickDir'](arg1);
}

export function PollLogs() {
  return window['go']['main']['App']['PollLogs']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartCore(arg1) {
  return window['go']['main']['App']['StartCore'](arg1);
}

export function StopCore() {
  return window['go']['main']['App']['StopCore']();
}

export function TailLog() {
  return window['go']['main']['App']['TailLog']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
